# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: |
  (?x)(
    # Python/system files
    ^.*/__init__\.py$|
    ^.*?/\.venv/.*$|
    ^.*?/node_modules/.*$|
    
    # Generated/test files
    ^.*?/\.pytest_cache/.*$|
    ^.*?/__pycache__/.*$|
    ^.*?/\.mypy_cache/.*$|
    ^.*?/\.ruff_cache/.*$
  )

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-toml  # Basic TOML syntax checking

-   repo: https://github.com/pappasam/toml-sort
    rev: v0.23.1
    hooks:
    -   id: toml-sort
        args: [--all]

-   repo: https://github.com/tamasfe/taplo
    rev: release/taplo-cli/0.8.1
    hooks:
    -   id: taplo
        args: ['fmt']  # TOML formatting
    -   id: taplo
        args: ['check']  # TOML linting

-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.1.11
    hooks:
    -   id: ruff
        args: [--fix]
    -   id: ruff-format

-   repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.3
    hooks:
    -   id: prettier
        types_or: [json, yaml]
        additional_dependencies:
          - prettier@3.0.3
