# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: |
  (?x)(
    # Python/system files
    ^.*?/\.venv/.*$|
    ^.*?/node_modules/.*$|

    # Generated/test files
    ^.*?/\.pytest_cache/.*$|
    ^.*?/__pycache__/.*$|
    ^.*?/\.mypy_cache/.*$|
    ^.*?/\.ruff_cache/.*$|

    # Package management
    ^.*?/poetry\.lock$|
    ^.*?/package-lock\.json$|
    ^.*?/pnpm-lock\.yaml$|

    # Build and test artifacts
    ^.*?/build/.*$|
    ^.*?/dist/.*$|
    ^.*?/\.coverage$|
    ^.*?/coverage\.xml$
  )

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-toml

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.5
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.3
    hooks:
      - id: prettier
        args: [--write]
        additional_dependencies:
          - prettier@3.0.3

  - repo: local
    hooks:
      - id: addlicense
        name: Add license headers
        entry: addlicense -c "Airbyte, Inc." -l apache -v -f LICENSE_SHORT
        language: golang
        additional_dependencies: [github.com/google/addlicense@v1.1.1]
        files: \.py$

      - id: poetry-check
        name: Check Poetry lockfile
        entry: poetry check
        language: system
        pass_filenames: false
        always_run: true

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        name: mypy
        entry: mypy
        args: [--config-file=mypy.ini, --show-column-numbers]
        files: ^airbyte_cdk/
        pass_filenames: true
        additional_dependencies: ["types-requests", "types-PyYAML"]
