site_name: Airbyte Python CDK
site_description: A framework for writing Airbyte Connectors
repo_url: https://github.com/airbytehq/airbyte-python-cdk
repo_name: airbytehq/airbyte-python-cdk

nav:
  - Home: index.md
  - API Reference:
    - Overview: api/index.md
    - Core: api/core.md
    - Models: api/models.md
    - Sources: api/sources.md
    - Destinations: api/destinations.md
  - Contributing: CONTRIBUTING.md
  - Release Management: RELEASES.md

theme:
  name: material
  palette:
    primary: blue
  logo: https://docs.airbyte.com/img/logo-dark.png
  favicon: https://docs.airbyte.com/img/favicon.png
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - search.highlight
    - search.share
    - content.code.copy

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [airbyte_cdk]
          options:
            show_source: true
            show_root_heading: true
            show_category_heading: true
            docstring_style: google
            merge_init_into_class: true
            show_if_no_docstring: true
            filters:
              - "!^_"  # exclude private members
              - "!^__"  # exclude special methods
          import:
            - https://docs.python.org/3/objects.inv

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - toc:
      permalink: true
