name: 'Check Docker Tag Exists'
description: 'Check if a Docker tag exists on DockerHub to prevent overwrites'
inputs:
  image_name:
    description: 'Docker image name (e.g. airbyte/source-declarative-manifest)'
    required: true
  tag:
    description: 'Docker tag to check'
    required: true
runs:
  using: "composite"
  steps:
    - name: "Check for existing tag (${{ inputs.image_name }}:${{ inputs.tag }})"
      shell: bash
      run: |
        tag="${{ inputs.image_name }}:${{ inputs.tag }}"
        if [ -z "$tag" ]; then
          echo "Error: tag is not set."
          exit 1
        fi
        echo "Checking if tag '$tag' exists on DockerHub..."
        if DOCKER_CLI_EXPERIMENTAL=enabled docker manifest inspect "$tag" > /dev/null 2>&1; then
          echo "The tag '$tag' already exists on DockerHub. Skipping publish to prevent overwrite."
          exit 1
        fi
        echo "No existing tag '$tag' found. Proceeding with publish."