name: SDM Docker Build

on:
  push:
    branches:
      - main
    paths:
      - 'airbyte_cdk/**'  # Any CDK changes could affect SDM
      - '.github/workflows/docker-build.yml'
      - 'Dockerfile'
  workflow_dispatch:
    inputs:
      version-tag:
        description: "Version tag for the image (e.g. 0.1.0)"
        required: false
        type: string

jobs:
  docker_build:
    name: Build and Publish source-declarative-manifest Docker Image
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            airbyte/source-declarative-manifest:latest
            airbyte/source-declarative-manifest:${{ github.sha }}
            ${{ github.event.inputs.version-tag != '' && format('airbyte/source-declarative-manifest:{0}', github.event.inputs.version-tag) || '' }}

      - name: Test image
        run: |
          docker pull airbyte/source-declarative-manifest:${{ github.sha }}
          docker run airbyte/source-declarative-manifest:${{ github.sha }} spec
