name: SCD Docker Build (Dev Images)

on:
  push:
  workflow_dispatch:

jobs:
  docker_publish:
    name: Build and Publish `source-declarative-manifest` Docker Image
    runs-on: ubuntu-latest
    permissions:
      id-token: write # IMPORTANT: this permission is mandatory for trusted publishing
      contents: write # Needed to upload artifacts to the release
    env: {}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: |
          docker login
          docker build -t airbyte/source-declarative-manifest:${{ github.sha }} .
          docker run airbyte/source-declarative-manifest:${{ github.sha }} --help
          docker run airbyte/source-declarative-manifest:${{ github.sha }} spec
          # docker push airbyte/source-declarative-manifest:${{ github.sha }}
