name: SDM Docker Build (Test)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  docker_build:
    name: Build and Publish source-declarative-manifest Docker Image
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}  # Only push on main
          tags: airbyte/source-declarative-manifest:test-${{ github.sha }}

      - name: Test image
        run: |
          docker pull airbyte/source-declarative-manifest:test-${{ github.sha }}
          docker run airbyte/source-declarative-manifest:test-${{ github.sha }} spec
