name: Dummy Check Result

on:
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/dummy_check_result.yml'

jobs:
  failure_check:
    name: "Dummy Check (fail)"
    runs-on: ubuntu-22.04
    permissions:
      checks: write
      contents: read
    steps:
      - name: Create Failure Check Run
        uses: LouisBrunner/checks-action@v1.6.1
        with:
          token: ${{ github.token }}
          name: "Dummy Check (fail custom)"
          status: completed
          conclusion: failure
          details_url: "https://www.google.com/search?q=failed"
          output: |
            {
              "title": "Test Report",
              "summary": "This is a dummy failure check.\nHTML Report URL: https://www.google.com/search?q=failed\n\nNote: The Details link above will go to the GitHub Actions run due to platform limitations."
            }
