name: Dummy Check Result

on:
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/dummy_check_result.yml'

jobs:
  success_check:
    name: "Dummy Check (1)"
    runs-on: ubuntu-22.04
    permissions:
      checks: write
      contents: read
    steps:
      - name: Create Success Check Run
        uses: LouisBrunner/checks-action@v1.6.1
        with:
          token: ${{ github.token }}
          name: "Dummy Check (success)"
          status: "completed"
          conclusion: "success"
          details_url: "https://www.google.com/search?q=success"
          output: |
            {
              "title": "Success Check",
              "summary": "This is a dummy success check."
            }

  failure_check:
    name: "Dummy Check (2)"
    runs-on: ubuntu-22.04
    permissions:
      checks: write
      contents: read
    steps:
      - name: Create Failure Check Run
        uses: LouisBrunner/checks-action@v1.6.1
        with:
          token: ${{ github.token }}
          name: "Dummy Check (fail)"
          status: "completed"
          conclusion: "failure"
          details_url: "https://www.google.com/search?q=failed"
          output: |
            {
              "title": "Failure Check",
              "summary": "This is a dummy failure check."
            }
