name: Dummy Check Result

on:
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/dummy_check_result.yml'

jobs:
  main_job:
    name: "Main Job"
    runs-on: ubuntu-22.04
    outputs:
      check_id: ${{ steps.create_check.outputs.check_id }}
    permissions:
      checks: write
      contents: read
    steps:
      - name: Create Initial Check Run
        id: create_check
        uses: LouisBrunner/checks-action@v1.6.1
        with:
          token: ${{ github.token }}
          name: "Test Results (Custom)"
          status: "in_progress"
          output: |
            {
              "title": "Test Results",
              "summary": "Running tests..."
            }
      - name: Sleep for a moment
        run: sleep 5

  update_check:
    needs: main_job
    name: "Update Check"
    runs-on: ubuntu-22.04
    permissions:
      checks: write
      contents: read
    steps:
      - name: Update Check Run
        uses: LouisBrunner/checks-action@v1.6.1
        with:
          token: ${{ github.token }}
          check_id: ${{ needs.main_job.outputs.check_id }}
          status: "completed"
          conclusion: "failure"
          details_url: "https://www.google.com/search?q=test-failure"
          output: |
            {
              "title": "Test Failed",
              "summary": "This is a test failure check with custom details URL."
            }
