name: Dummy Check Result

on:
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/dummy_check_result.yml'

jobs:
  test_check:
    name: "Test Check"
    runs-on: ubuntu-22.04
    permissions:
      checks: write
      contents: read
    steps:
      - name: Create Independent Check Run
        uses: LouisBrunner/checks-action@v1.6.1
        with:
          token: ${{ github.token }}
          name: "External Test Report Link"
          status: completed
          conclusion: failure
          details_url: "https://www.google.com/search?q=test-failure"
          output: |
            {
              "title": "External Test Report",
              "summary": "Click 'Details' to view the external test report."
            }
