name: Dummy Commit Status

on:
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/dummy_check_result.yml'

jobs:
  failure_status:
    name: "Dummy Status (fail)"
    runs-on: ubuntu-22.04
    permissions:
      contents: write  # Required for creating commit statuses
    steps:
      - name: Create Failure Status
        env:
          GH_TOKEN: ${{ secrets.GH_PAT_MAINTENANCE_OCTAVIA }}
        run: |
          HEAD_SHA="${{ github.event.pull_request.head.sha || github.sha }}"
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            repos/${{ github.repository }}/statuses/$HEAD_SHA \
            -f state="failure" \
            -f target_url="https://www.google.com/search?q=failed" \
            -f description="Click Details to view the test report" \
            -f context="Test Report: Dummy Connector"
