name: Dummy Check Result

on:
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/dummy_check_result.yml'

jobs:
  failure_check:
    name: "Dummy Job"
    runs-on: ubuntu-22.04
    permissions:
      checks: write
      contents: read
    steps:
      - name: Create Initial Check Run
        uses: LouisBrunner/checks-action@v1.6.1
        with:
          token: ${{ github.token }}
          name: "Dummy Check"
          status: "in_progress"
          output: |
            {
              "title": "Test Check",
              "summary": "Running test check..."
            }

      - name: Sleep for a moment
        run: sleep 5

      - name: Update Check Run with Details URL
        uses: LouisBrunner/checks-action@v1.6.1
        with:
          token: ${{ github.token }}
          name: "Dummy Check"
          status: "completed"
          conclusion: "failure"
          details_url: "https://www.google.com/search?q=test-failure"
          output: |
            {
              "title": "Test Failed",
              "summary": "This is a test failure check with custom details URL."
            }
