name: Generate Docs

on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  preview_docs:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Get tool versions
        uses: marocchino/tool-versions-action@v1
        id: tool-versions
      - name: Set up Poetry
        uses: Gr1N/setup-poetry@v9
        with:
          poetry-version: ${{ steps.tool-versions.outputs.poetry }}
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ steps.tool-versions.outputs.python }}
          cache: "poetry"

      - name: Install dependencies
        run: poetry install --all-extras

      - name: Generate documentation
        run: |
          set -e
          poetry run poe docs-generate
          if [ ! -d "docs/generated" ]; then
            echo "Error: Documentation generation failed - docs/generated directory not found"
            exit 1
          fi

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload generated documentation
          path: "docs/generated"
