name: Python Packaging

on:
  push:

  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: hynek/build-and-inspect-python-package@v2

  publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    needs: [build]
    permissions:
      id-token: write # IMPORTANT: this permission is mandatory for trusted publishing
      contents: write # Needed to upload artifacts to the release
    environment:
      name: PyPI
      url: "https://pypi.org/p/airbyte-cdk"
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: Packages
          path: dist
      - name: Attach Wheel to GitHub Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/*.whl
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true

      - name: Publish to PyPI (${{vars.PYPI_PUBLISH_URL}})
        uses: pypa/gh-action-pypi-publish@v1.12.2
        with:
          # Can be toggled at the repository level between `https://upload.pypi.org/legacy/` and `https://test.pypi.org/legacy/`
          repository-url: ${{vars.PYPI_PUBLISH_URL}}

  # TODO: Need to test this on the other workflow first, then update here when we have
  #       something that works.
  docker_publish:
    name: Build and Publish `source-declarative-manifest` Docker Image
    runs-on: ubuntu-latest
    needs: [build]
    permissions:
      id-token: write # IMPORTANT: this permission is mandatory for trusted publishing
      contents: write # Needed to upload artifacts to the release
    environment:
      name: Docker Hub
      url: "https://hub.docker.com/r/airbytehq/airbyte-cdk"
    env:
      # TODO: Clean this up with a real version tag, remove the 'refs/tags/v' prefix
      VERSION: ${{ github.ref }}
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - run: |
          docker login
          docker build -t airbyte/source-declarative-manifest:${VERSION} .
          docker push airbyte/source-declarative-manifest:${VERSION}
