name: Linters

on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  ruff-lint-check:
    name: Ruff Lint Check
    runs-on: ubuntu-24.04
    steps:
      # Common steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Poetry
        uses: Gr1N/setup-poetry@v9
        with:
          poetry-version: "1.8.4"
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "poetry"
      - name: Install dependencies
        run: poetry install --all-extras

      # Job-specifc step(s):
      - name: Run lint check
        run: poetry run ruff check .

  ruff-format-check:
    name: Ruff Format Check
    runs-on: ubuntu-24.04
    steps:
      # Common steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Poetry
        uses: Gr1N/setup-poetry@v9
        with:
          poetry-version: "1.8.4"
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "poetry"
      - name: Install dependencies
        run: poetry install --all-extras

      # Job-specifc step(s):
      - name: Check code format
        run: poetry run ruff format --check .

  mypy-check:
    name: MyPy Check
    runs-on: ubuntu-24.04
    steps:
      # Common steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Poetry
        uses: Gr1N/setup-poetry@v9
        with:
          poetry-version: "1.8.4"
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "poetry"
      - name: Install dependencies
        run: poetry install --all-extras

      # Job-specific step(s):
      - uses: tsuyoshicho/action-mypy@v5
        with:
          github_token: ${{ secrets.github_token }}
          # Change reviewdog reporter if you need [github-pr-check,github-check,github-pr-review].
          reporter: github-pr-review
          level: error
          execute_command: 'poetry run mypy'
          fail_on_error: true
          target: airbyte_cdk
